import { Header } from "@/components/Header";
import "./globals.css";
import { NextAuthProvider } from "./providers";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const session = await unstable_getServerSession(authOptions);
  // console.log(session)

  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <Header />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
